### ISSUE TITLE
content inside <section class="tab-content'> does not show when tab is clicked

### ISSUE THREAD

**Issue by thecforsythe** [nerdbetter/portfolio#13]
content is not visible in all media sizes

**Comment by thecforsythe** [comment]
removed a from $('.navList li') on line 8 animations.js

**Comment by thecforsythe** [comment]
I somehow broke this fix and I am absolutley stumped why it is no longer displaying. I noticed my fix not working  after I inserted a test <p> tag at line 73 between the section and script tag and I changed some single quotes to doubles at the bottom of the index page around the scripts. after I noticed the problem, I did undo but this did not fix the problem.

**Comment by nerdbetter** [comment]
fixed
